#!/usr/bin/env bash
set -euo pipefail

ROOT="${1:-/home/ubuntu/baselayer}"
BUNDLE="${BASELAYER_BUNDLE_PATH:-/home/ubuntu/baselayer-basic-profiles.tar.gz}"
LOG="${BASELAYER_PREPARE_LOG:-/home/ubuntu/basic-profiles-prepare.log}"

exec > >(tee -a "$LOG") 2>&1

echo "[prepare-basic] started $(date -Is)"
sudo rm -rf "$ROOT"
mkdir -p "$ROOT"
tar -xzf "$BUNDLE" -C "$ROOT"
cd "$ROOT"

# Optional: clone depot_tools for BASELAYER_BUILD_CUSTOM_CHROMIUM=1 (does not fetch Chromium src).
if [[ "${BASELAYER_FETCH_DEPOT_TOOLS:-0}" == "1" ]] && [[ ! -x "${DEPOT_TOOLS_DIR:-$HOME/depot_tools}/gn" ]]; then
  _dt="${DEPOT_TOOLS_DIR:-$HOME/depot_tools}"
  echo "[prepare-basic] cloning depot_tools into $_dt"
  git clone --depth 1 https://chromium.googlesource.com/chromium/tools/depot_tools.git "$_dt"
  export DEPOT_TOOLS_DIR="$_dt"
  export PATH="$DEPOT_TOOLS_DIR:$PATH"
  unset _dt
fi

# Stage a prebuilt headless_shell tree (tarball URL, tarball path, bundle path, or ~/.baselayer-custenv).
CUSTENV="${BASELAYER_CUSTENV_PATH:-$HOME/.baselayer-custenv}"
if [[ -f "$CUSTENV" ]]; then
  # shellcheck disable=SC1090
  source "$CUSTENV" || true
fi
if [[ -x "$ROOT/scripts/bench/adhoc/stage-custom-chromium-runtime.sh" ]]; then
  bash "$ROOT/scripts/bench/adhoc/stage-custom-chromium-runtime.sh" "$ROOT" || true
fi
if [[ -f "$CUSTENV" ]]; then
  # shellcheck disable=SC1090
  source "$CUSTENV" || true
fi

if [[ -f /home/ubuntu/build-headless-shell-rootfs.sh ]]; then
  echo "[prepare-basic] applying uploaded rootfs builder override"
  cp /home/ubuntu/build-headless-shell-rootfs.sh "$ROOT/scripts/firecracker/build-headless-shell-rootfs.sh"
  chmod +x "$ROOT/scripts/firecracker/build-headless-shell-rootfs.sh"
fi

CUSTOM_SHELL_PATH="${FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM:-}"
if [[ -n "$CUSTOM_SHELL_PATH" ]]; then
  echo "[prepare-basic] custom shell resolved to $CUSTOM_SHELL_PATH"
fi

if [[ "${BASELAYER_BUILD_CUSTOM_CHROMIUM:-0}" == "1" ]]; then
  if [[ -z "${BASELAYER_CHROMIUM_SRC_DIR:-}" || ! -f "${BASELAYER_CHROMIUM_SRC_DIR:-}/BUILD.gn" ]]; then
    echo "[prepare-basic] custom chromium requested, but BASELAYER_CHROMIUM_SRC_DIR is missing or is not a Chromium source tree: ${BASELAYER_CHROMIUM_SRC_DIR:-unset}" >&2
    exit 1
  fi
  if [[ -n "${DEPOT_TOOLS_DIR:-}" && -d "${DEPOT_TOOLS_DIR:-}" ]]; then
    export PATH="$DEPOT_TOOLS_DIR:$PATH"
  fi
  if ! command -v gn >/dev/null 2>&1 || ! command -v autoninja >/dev/null 2>&1; then
    echo "[prepare-basic] custom chromium requested, but gn/autoninja are not on PATH. Set DEPOT_TOOLS_DIR." >&2
    exit 1
  fi
elif [[ -n "$CUSTOM_SHELL_PATH" ]]; then
  if [[ ! -x "$CUSTOM_SHELL_PATH" ]]; then
    echo "[prepare-basic] FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM is not executable: $CUSTOM_SHELL_PATH" >&2
    exit 1
  fi
fi

echo "[prepare-basic] bootstrap firecracker host $(date -Is)"
sudo env FIRECRACKER_BROWSER_PROFILE=optimized bash "$ROOT/scripts/bench/bootstrap-firecracker-linux.sh" "$ROOT"
sudo chown -R "$(id -u):$(id -g)" "$ROOT/artifacts" "$ROOT/node_modules" "$ROOT/package-lock.json" 2>/dev/null || true
sudo chown -R "$(id -u):$(id -g)" "$ROOT" 2>/dev/null || true

if [[ "${BASELAYER_USE_PLAYWRIGHT_HEADLESS_AS_CUSTOM:-0}" == "1" && -z "$CUSTOM_SHELL_PATH" ]]; then
  echo "[prepare-basic] resolving installed Playwright chromium-headless-shell as custom runtime"
  PLAYWRIGHT_SEARCH_DIRS=()
  for dir in /root/.cache/ms-playwright "$HOME/.cache/ms-playwright" "$ROOT/node_modules"; do
    if sudo test -d "$dir" 2>/dev/null; then
      PLAYWRIGHT_SEARCH_DIRS+=("$dir")
    fi
  done
  CUSTOM_SHELL_PATH="$(
    sudo find "${PLAYWRIGHT_SEARCH_DIRS[@]}" \
      -type f \( -name chrome-headless-shell -o -name headless_shell \) -print -quit 2>/dev/null || true
  )"
  if [[ -z "$CUSTOM_SHELL_PATH" ]] || ! sudo test -f "$CUSTOM_SHELL_PATH" 2>/dev/null; then
    echo "[prepare-basic] could not find installed Linux chromium-headless-shell for BASELAYER_USE_PLAYWRIGHT_HEADLESS_AS_CUSTOM=1" >&2
    exit 1
  fi
  sudo chmod +x "$CUSTOM_SHELL_PATH" 2>/dev/null || true
  if ! sudo test -x "$CUSTOM_SHELL_PATH" 2>/dev/null; then
    echo "[prepare-basic] resolved Playwright custom shell is not executable: $CUSTOM_SHELL_PATH" >&2
    exit 1
  fi
  CUSTOM_RUNTIME_SRC_DIR="$(dirname "$CUSTOM_SHELL_PATH")"
  CUSTOM_RUNTIME_STAGE="$ROOT/artifacts/custom-chromium-runtime/playwright-headless-shell"
  rm -rf "$CUSTOM_RUNTIME_STAGE"
  mkdir -p "$CUSTOM_RUNTIME_STAGE"
  sudo cp -a "$CUSTOM_RUNTIME_SRC_DIR"/. "$CUSTOM_RUNTIME_STAGE"/
  sudo chown -R "$(id -u):$(id -g)" "$ROOT/artifacts/custom-chromium-runtime" 2>/dev/null || true
  CUSTOM_SHELL_BASENAME="$(basename "$CUSTOM_SHELL_PATH")"
  CUSTOM_SHELL_PATH="$CUSTOM_RUNTIME_STAGE/$CUSTOM_SHELL_BASENAME"
  chmod +x "$CUSTOM_SHELL_PATH" 2>/dev/null || true
  export FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM="$CUSTOM_SHELL_PATH"
  {
    echo "# Generated by prepare-basic-profiles-host.sh"
    printf "export FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM=%q\n" "$CUSTOM_SHELL_PATH"
  } > "${BASELAYER_CUSTENV_PATH:-$HOME/.baselayer-custenv}"
  chmod 600 "${BASELAYER_CUSTENV_PATH:-$HOME/.baselayer-custenv}" 2>/dev/null || true
  echo "[prepare-basic] using Playwright custom shell=$CUSTOM_SHELL_PATH"
fi

echo "[prepare-basic] host tuning $(date -Is)"
if [[ -f "$ROOT/scripts/bench/bootstrap-baremetal-linux.sh" ]]; then
  sudo bash "$ROOT/scripts/bench/bootstrap-baremetal-linux.sh" || true
else
  echo "[prepare-basic] host tuning script not present in bundle; skipping"
fi

METRICS_DIR="$ROOT/artifacts/firecracker/rootfs-build-metrics-basic"
CHROOT_CACHE_TAR="$ROOT/artifacts/firecracker/cache/noble-minbase-chroot-basic.tar.gz"
mkdir -p "$METRICS_DIR" "$(dirname "$CHROOT_CACHE_TAR")"

if [[ "${BASELAYER_BUILD_CUSTOM_CHROMIUM:-0}" == "1" ]]; then
  echo "[prepare-basic] custom chromium build requested $(date -Is)"
  if [[ -z "${BASELAYER_CHROMIUM_SRC_DIR:-}" ]]; then
    echo "[prepare-basic] BASELAYER_CHROMIUM_SRC_DIR is required when BASELAYER_BUILD_CUSTOM_CHROMIUM=1" >&2
    exit 1
  fi
  if [[ -n "${DEPOT_TOOLS_DIR:-}" && -d "${DEPOT_TOOLS_DIR:-}" ]]; then
    export PATH="$DEPOT_TOOLS_DIR:$PATH"
  fi
  CUSTOM_BUILD_METRICS="$ROOT/artifacts/firecracker/custom-chromium-build-metrics.json"
  BASELAYER_CHROMIUM_BUILD_METRICS_PATH="$CUSTOM_BUILD_METRICS" \
    bash "$ROOT/scripts/chromium/build-custom-headless-shell.sh"
  CUSTOM_SHELL_PATH="$(python3 - "$CUSTOM_BUILD_METRICS" <<'PY'
import json
import sys

with open(sys.argv[1], "r", encoding="utf-8") as f:
    data = json.load(f)
print(data.get("binaryPath", ""))
PY
)"
  if [[ -z "$CUSTOM_SHELL_PATH" || ! -x "$CUSTOM_SHELL_PATH" ]]; then
    echo "[prepare-basic] custom chromium build did not produce an executable binary: $CUSTOM_SHELL_PATH" >&2
    exit 1
  fi
  export FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM="$CUSTOM_SHELL_PATH"
  echo "[prepare-basic] custom chromium binary=$CUSTOM_SHELL_PATH"
elif [[ -n "$CUSTOM_SHELL_PATH" ]]; then
  if [[ ! -x "$CUSTOM_SHELL_PATH" ]]; then
    echo "[prepare-basic] FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM is not executable: $CUSTOM_SHELL_PATH" >&2
    exit 1
  fi
  echo "[prepare-basic] using prebuilt custom chromium binary=$CUSTOM_SHELL_PATH"
fi

build_rootfs() {
  local suffix="$1"
  local launch_profile="$2"
  local metrics_name="$3"
  local save_cache="$4"
  local use_cache="$5"

  echo "[prepare-basic] build rootfs suffix=${suffix:-baseline} profile=${launch_profile:-none} $(date -Is)"
  sudo env \
    FIRECRACKER_ROOTFS_CHROOT_CACHE_TAR="$CHROOT_CACHE_TAR" \
    FIRECRACKER_ROOTFS_SAVE_CHROOT_CACHE="$save_cache" \
    FIRECRACKER_ROOTFS_USE_CHROOT_CACHE="$use_cache" \
    FIRECRACKER_ROOTFS_SKIP_HOST_APT="$use_cache" \
    FIRECRACKER_HEADLESS_SHELL_PATH="" \
    FIRECRACKER_CHROMIUM_PATH="" \
    FIRECRACKER_CHROME_INSTRUMENTATION_PROFILE=none \
    FIRECRACKER_CHROME_LAUNCH_PROFILE="$launch_profile" \
    FIRECRACKER_ROOTFS_VARIANT_SUFFIX="$suffix" \
    FIRECRACKER_ROOTFS_BUILD_METRICS_PATH="$METRICS_DIR/$metrics_name" \
    bash "$ROOT/scripts/firecracker/build-headless-shell-rootfs.sh" "$ROOT"
  sudo chown -R "$(id -u):$(id -g)" "$ROOT/artifacts" 2>/dev/null || true
}

build_rootfs "" "" "rootfs-baseline.json" 1 0
build_rootfs "kernel-startup-prune" "kernel-startup-prune" "rootfs-kernel-startup-prune.json" 0 1
build_rootfs "kernel-balanced" "kernel-balanced" "rootfs-kernel-balanced.json" 0 1
if [[ "${BASELAYER_BUILD_ASYNC_LINUX_ROOTFS:-0}" == "1" ]]; then
  build_rootfs "async-manual-gengar" "async-parity-manual-gengar" "rootfs-async-manual-gengar.json" 0 1
  build_rootfs "async-manual-dragonite" "async-parity-manual-dragonite" "rootfs-async-manual-dragonite.json" 0 1
fi

build_custom_rootfs() {
  local suffix="$1"
  local launch_profile="$2"
  local metrics_name="$3"

  echo "[prepare-basic] build custom rootfs suffix=$suffix profile=${launch_profile:-none} $(date -Is)"
  sudo env \
    FIRECRACKER_ROOTFS_CHROOT_CACHE_TAR="$CHROOT_CACHE_TAR" \
    FIRECRACKER_ROOTFS_SAVE_CHROOT_CACHE=0 \
    FIRECRACKER_ROOTFS_USE_CHROOT_CACHE=1 \
    FIRECRACKER_ROOTFS_SKIP_HOST_APT=1 \
    FIRECRACKER_HEADLESS_SHELL_PATH="$CUSTOM_SHELL_PATH" \
    FIRECRACKER_CHROMIUM_PATH="" \
    FIRECRACKER_CHROME_INSTRUMENTATION_PROFILE=none \
    FIRECRACKER_CHROME_LAUNCH_PROFILE="$launch_profile" \
    FIRECRACKER_ROOTFS_VARIANT_SUFFIX="$suffix" \
    FIRECRACKER_ROOTFS_BUILD_METRICS_PATH="$METRICS_DIR/$metrics_name" \
    bash "$ROOT/scripts/firecracker/build-headless-shell-rootfs.sh" "$ROOT"
  sudo chown -R "$(id -u):$(id -g)" "$ROOT/artifacts" 2>/dev/null || true
}

if [[ -n "$CUSTOM_SHELL_PATH" ]]; then
  build_custom_rootfs "custom-shell-baseline" "" "rootfs-custom-shell-baseline.json"
  build_custom_rootfs "custom-shell-startup-prune" "kernel-startup-prune" "rootfs-custom-shell-startup-prune.json"
  build_custom_rootfs "custom-shell-async-manual" "async-parity-manual-custom-shell" "rootfs-custom-shell-async-manual.json"
  build_custom_rootfs "custom-shell-kernel-balanced" "kernel-balanced" "rootfs-custom-shell-kernel-balanced.json"
fi

echo "[prepare-basic] verify assets $(date -Is)"
ls -lh "$ROOT/artifacts/firecracker"/vmlinux "$ROOT/artifacts/firecracker"/rootfs*.ext4
node "$ROOT/dist/bench/verify-firecracker-assets.js" || true
if [[ -n "$CUSTOM_SHELL_PATH" ]]; then
  BENCH_ENABLE_FIRECRACKER=1 \
    BENCH_PROFILE_IDS="BaseLayer-Abra-custom-shell-baseline,BaseLayer-Kadabra-custom-shell-startup-prune,BaseLayer-Alakazam-custom-shell-async-manual,BaseLayer-Ditto-custom-shell-kernel-balanced" \
    FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM="$CUSTOM_SHELL_PATH" \
    node "$ROOT/dist/bench/verify-firecracker-assets.js"
fi
echo "[prepare-basic] done $(date -Is)"
