#!/usr/bin/env bash
# Extract or locate a prebuilt headless_shell / chrome-headless-shell tree and set
# FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM for prepare + verify preflight.
#
# Usage: ROOT=/home/ubuntu/baselayer bash stage-custom-chromium-runtime.sh
#    or: source this file with one arg: repo root path.
#
# Inputs (first match wins):
#   1) Tree already under BASELAYER_CUSTOM_CHROMIUM_STAGING_DIR (default
#      $ROOT/artifacts/custom-chromium-runtime), e.g. shipped inside the bundle.
#   2) BASELAYER_CUSTOM_CHROMIUM_TAR_URL — curl download then tar -xaf.
#   3) BASELAYER_CUSTOM_CHROMIUM_TAR — path to tarball on disk.
#   4) /home/ubuntu/custom-chromium-runtime.tar.gz if present.
#
# If FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM is already set to an executable, exits 0.

set -euo pipefail

ROOT="${1:-$(cd "$(dirname "$0")/../../.." && pwd)}"
STAGING="${BASELAYER_CUSTOM_CHROMIUM_STAGING_DIR:-"$ROOT/artifacts/custom-chromium-runtime"}"
DEFAULT_TAR="${BASELAYER_CUSTOM_CHROMIUM_TAR:-$HOME/custom-chromium-runtime.tar.gz}"
CUSTENV_OUT="${BASELAYER_CUSTENV_PATH:-$HOME/.baselayer-custenv}"

discover_custom_shell_binary() {
  local search_root="$1"
  local bin=""
  bin="$(find "$search_root" -type f \( -name headless_shell -o -name chrome-headless-shell \) 2>/dev/null | head -1)"
  if [[ -n "$bin" && -f "$bin" ]]; then
    chmod +x "$bin" 2>/dev/null || true
    echo "$bin"
    return 0
  fi
  return 1
}

if [[ -n "${FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM:-}" && -x "${FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM:-}" ]]; then
  echo "[stage-custom-chromium] using existing FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM=$FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM"
  exit 0
fi

mkdir -p "$STAGING"

if [[ -n "${BASELAYER_CUSTOM_CHROMIUM_TAR_URL:-}" ]]; then
  echo "[stage-custom-chromium] downloading BASELAYER_CUSTOM_CHROMIUM_TAR_URL"
  tmp="$(mktemp)"
  curl -fsSL "$BASELAYER_CUSTOM_CHROMIUM_TAR_URL" -o "$tmp"
  tar -xaf "$tmp" -C "$STAGING"
  rm -f "$tmp"
elif [[ -n "${BASELAYER_CUSTOM_CHROMIUM_TAR:-}" && -f "${BASELAYER_CUSTOM_CHROMIUM_TAR:-}" ]]; then
  echo "[stage-custom-chromium] extracting BASELAYER_CUSTOM_CHROMIUM_TAR=$BASELAYER_CUSTOM_CHROMIUM_TAR"
  tar -xaf "$BASELAYER_CUSTOM_CHROMIUM_TAR" -C "$STAGING"
elif [[ -f "$DEFAULT_TAR" ]]; then
  echo "[stage-custom-chromium] extracting $DEFAULT_TAR"
  tar -xaf "$DEFAULT_TAR" -C "$STAGING"
fi

if bin="$(discover_custom_shell_binary "$STAGING")"; then
  export FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM="$bin"
  {
    echo "# Generated by stage-custom-chromium-runtime.sh; source before bench: verify or matrix."
    printf "export FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM=%q\n" "$bin"
  } > "$CUSTENV_OUT"
  chmod 600 "$CUSTENV_OUT" 2>/dev/null || true
  echo "[stage-custom-chromium] FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM=$FIRECRACKER_HEADLESS_SHELL_PATH_CUSTOM"
  echo "[stage-custom-chromium] wrote $CUSTENV_OUT (source it in new shells)"
  exit 0
fi

echo "[stage-custom-chromium] FAILED: no headless_shell or chrome-headless-shell under $STAGING" >&2
echo "[stage-custom-chromium] Pack your out/ directory (with icudtl.dat, *.pak, snapshot blobs) and either:" >&2
echo "  scp custom-chromium-runtime.tar.gz ubuntu@host:/home/ubuntu/   (auto-detected), or" >&2
echo "  set BASELAYER_CUSTOM_CHROMIUM_TAR or BASELAYER_CUSTOM_CHROMIUM_TAR_URL, or" >&2
echo "  include artifacts/custom-chromium-runtime/ inside the baselayer bundle." >&2
exit 1
