#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
cd "$ROOT_DIR"

export BENCH_CONCURRENCY_STEP="${BENCH_CONCURRENCY_STEP:-1}"
export BENCH_SUCCESS_THRESHOLD="${BENCH_SUCCESS_THRESHOLD:-1}"
export BENCH_WARMUP_ITERATIONS="${BENCH_WARMUP_ITERATIONS:-1}"
export BENCH_SOAK_SECONDS="${BENCH_SOAK_SECONDS:-15}"
export BENCH_ACTIVE_SESSION_RATIO="${BENCH_ACTIVE_SESSION_RATIO:-0.5}"
export BENCH_ACTIVE_ROUNDS_PER_SESSION="${BENCH_ACTIVE_ROUNDS_PER_SESSION:-4}"
export BENCH_ACTIVE_PAUSE_MS="${BENCH_ACTIVE_PAUSE_MS:-750}"
export BENCH_PRESSURE_SAMPLE_MS="${BENCH_PRESSURE_SAMPLE_MS:-1000}"
export BENCH_MIN_FREE_MEMORY_MB="${BENCH_MIN_FREE_MEMORY_MB:-2048}"
export BENCH_SESSION_MEMORY_LIMIT_MB="${BENCH_SESSION_MEMORY_LIMIT_MB:-512}"
export BENCH_SESSION_MEMORY_RESERVATION_MB="${BENCH_SESSION_MEMORY_RESERVATION_MB:-384}"
export BENCH_SESSION_ADMISSION_MEMORY_MB="${BENCH_SESSION_ADMISSION_MEMORY_MB:-192}"
export BENCH_SESSION_SHM_LIMIT_MB="${BENCH_SESSION_SHM_LIMIT_MB:-128}"
export BENCH_SESSION_ADMISSION_SHM_MB="${BENCH_SESSION_ADMISSION_SHM_MB:-48}"
export BENCH_SESSION_RENDERER_LIMIT="${BENCH_SESSION_RENDERER_LIMIT:-6}"
export BENCH_WARM_RENDERER_BUDGET="${BENCH_WARM_RENDERER_BUDGET:-3}"
export BENCH_WARM_POOL_RESERVE="${BENCH_WARM_POOL_RESERVE:-2}"
export BENCH_WARM_RUNTIME_SETTLE_MS="${BENCH_WARM_RUNTIME_SETTLE_MS:-400}"
export BENCH_WARM_POOL_FILL_CONCURRENCY="${BENCH_WARM_POOL_FILL_CONCURRENCY:-8}"
export RUNTIME_IMAGE="${RUNTIME_IMAGE:-baselayer-runtime:local}"

mkdir -p data/benchmarks/gcp

npm install
npm run build
sudo docker build -f Dockerfile.runtime -t "$RUNTIME_IMAGE" .

for target in 20 30 50; do
  export BENCH_MAX_CONCURRENCY="$target"
  export BENCH_MAX_SESSIONS="$target"
  export BENCH_MAX_RENDERERS="$(( target * 6 ))"
  export BENCH_WARM_POOL_SIZE="$(( target < 8 ? target : 8 ))"

  out="data/benchmarks/gcp/density-c${target}.json"
  echo "Running density benchmark at concurrency ${target}"
  node dist/bench/density.js | tee "$out"
done
